# syntax=docker/dockerfile:1.4
FROM python:3.11-slim

WORKDIR /app

# Step 1: Copy dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Step 2: Copy app source
COPY . .

CMD ["python", "app.py"]
